# Generated by Django 4.2.7 on 2023-12-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="season",
            field=models.CharField(
                blank=True, default="2023/24", max_length=7, null=True
            ),
        ),
    ]
