# Generated by Django 4.2.7 on 2023-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_league_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="season",
            field=models.CharField(default="2023/24", max_length=7),
        ),
    ]
