# Generated by Django 4.2.7 on 2024-01-02 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_fixture_time_alter_table_league_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Table",
            new_name="LeagueTable",
        ),
    ]
