# Generated by Django 4.2.7 on 2024-01-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_leaguetable_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
