# Generated by Django 4.2.7 on 2024-01-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_league_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="home.league",
            ),
        ),
    ]
