# Generated by Django 4.2.7 on 2024-01-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_team_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_slug",
            field=models.SlugField(default=""),
        ),
    ]
