# Generated by Django 4.2.7 on 2024-02-19 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_team_team_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="href_str",
        ),
        migrations.RemoveField(
            model_name="league",
            name="season",
        ),
    ]
