# Generated by Django 4.2.7 on 2024-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_team_team_slug"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="leagues",
            field=models.ManyToManyField(related_name="profiles", to="home.league"),
        ),
        migrations.AddField(
            model_name="profile",
            name="teams",
            field=models.ManyToManyField(related_name="profiles", to="home.team"),
        ),
    ]
