# Generated by Django 4.2.7 on 2024-02-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_team_team_slug"),
        ("users", "0002_profile_leagues_profile_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="leagues",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="profiles", to="home.league"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="teams",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="profiles", to="home.team"
            ),
        ),
    ]
