# Generated by Django 4.2.7 on 2024-02-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_team_team_slug"),
        ("users", "0003_alter_profile_leagues_alter_profile_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="home.team"
            ),
        ),
    ]
